### ISSUE TITLE
[Question] Is it possible to disable folders creation?

### ISSUE THREAD

**Issue by HYDesmondLiu** [ugr-sail/sinergym#276]
### Question ❓

How could I disable excessive folder creation running experiments? e.g. "Eplus-env-5Zone-cool-continuous-stochastic-v1-res1/". It makes finding files difficult and occupies a lot of hard disk space.

### Checklist

- [X] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

**Comment by AlejandroCN7** [comment]
Hi @HYDesmondLiu,

The Sinergym output folder cannot be disabled, since it shows results of the experiment (both in EnergyPlus format and outputs from the framework itself if the logger is enabled or a model is trained). However, you can reduce the number of the last n episodes it has run. This value defaults to 10, and you could reduce it so that those folders take less space.

Documentation about that parameter is [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#maximum-episode-data-stored-in-sinergym-output) and an example about how you can modify a parameter in an environment is [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/notebooks/change_environment.html#Changing-an-environment-registered-in-Sinergym) (using that paramter instead of reward parameter, for example).
