### ISSUE TITLE
Create new variables

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#278]
### Question ❓

Dear @AlejandroCN7,

I want to perform Q-learning with sinergym to compare those results with DRL. Therefore I want to a simulation with a small number of observation variables. I want to include inside temperature but since these variables are continuous I want to use bins to make the Q-table not infinity large. For example, a temperature of 19.2876 must be in the bin  (19.125-19.375) and therefore to 19.25. In this case there would be 61 bins.

How can I add such a new created variable to the observation space in sinergym? I am not sure how this works since the temperatures are still needed to be simulated before you can assign them to a bin.

kind regards,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

The observation variables must belong to the building, otherwise the simulation will fail. The simulation that is executed will always work with continuous values since that is what the simulator returns. You will have to take the observations of each timestep and process them yourself to get them into a bin as you said.

**Comment by MichielKempkens** [comment]
hi @AlejandroCN7,

Thank you for your answer. 

How would I add such a variable to the observation space since this would not be available in the [variables](https://github.com/ugr-sail/sinergym/tree/main/sinergym/data/variablesl) file. 

Best, 
Michiel

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Actually, all observation variables are directly related with simulation variables, so it is not possible to observe variables that are not present in RDD file. In any case, I think it is more convenient to process the observation received in order to calculate the bin. You could implement a wrapper to process observation as you want.

**Comment by MichielKempkens** [comment]
thank you!
