### ISSUE TITLE
New weather/IDF file

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#288]
### Question ❓

Dear @AlejandroCN7,

Sorry to bother you again today. After installing everything again it is working fine again. However, I am trying to perform simulations with my own weather and idf file. After following the steps describes [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#observation-action-spaces), It does not work. It cannot seem to find the new added files. It can find all other weather files but not the new ones. The error is :

![image](https://user-images.githubusercontent.com/63644603/219344379-4751f396-6073-4949-9549-ba2553dae940.png)

What is the reason that the files cannot be found? Does it get the files from some other folder than the folder on the left?

Best,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens!
Can you show me the parameter's values of `gym.make`construction?

**Comment by MichielKempkens** [comment]
![image](https://user-images.githubusercontent.com/63644603/219357649-6377966d-9279-4ea8-ac36-03071213fc25.png)

**Comment by MichielKempkens** [comment]
Hi @AlejandroCN7 ,

The parameters look like this:

![image](https://user-images.githubusercontent.com/63644603/219604104-aa74cbb6-149a-43a0-8765-fde28f1c92bb.png)

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens!
Are you using jupyter notebooks? Notebooks doesn't use sinergym local repository.

When we update something locally in Sinergym, and we want to use those local updates in notebooks, the kernel will execute it with the latest pip version of Sinergym.

This is because the sinergym import on a notebook use the latest installation in pypi repository instead of the local files as with the rest of the project (with py scripts). I don't now why this happens exactly.

So, to fix this we have to do the following:

1. Create a temporal box code on any notebook to run the following:
```
!pip uninstall sinergym -y
!pip install -e <local_repository_root_path>[extras]
```

For example, if your notebook is in `sinergym/examples`, it would be: `!pip install -e ../.[extras]`

2. You can delete that code box since it will not be needed anymore.
3. **IMPORTANT**: Restart the kernel, otherwise the changes will not be applied.

Let me know if your problem is solved,
Regards.

**Comment by MichielKempkens** [comment]
It works! You are amazing! Thank you so much for your help @AlejandroCN7 !
