### ISSUE TITLE
Controllers for other buildings?

### ISSUE THREAD

**Issue by kad99kev** [ugr-sail/sinergym#335]
### Question ❓

Hello, I was wondering if there is information for setpoint ranges for other buildings as I am looking to create controllers for them.

For example [5Zone](https://github.com/ugr-sail/sinergym/blob/f611c859d9d91837872305accd4917ffd4b16f61/sinergym/utils/controllers.py#L32) and [Datacenter](https://github.com/ugr-sail/sinergym/blob/f611c859d9d91837872305accd4917ffd4b16f61/sinergym/utils/controllers.py#L77) have a recommended setpoint, is there a recommended setpoint for Warehouse and Offices? I could create a controller for them and create a PR if you could help me with this.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

**Comment by AlejandroCN7** [comment]
Hi @kad99kev!

I have been looking into this topic. In this [page](https://www.energycodes.gov/prototype-building-models), there are zip files with information about ASHRAE Standard in some buildings such as Office and Warehouse. However, other buildings such as *ShopWithVandBattery* is not covered in that page due to the fact that we have extracted from Energyplus repository directly.

If I get any more information about it, I will contact you through this issue.

Thank you so much!

**Comment by kad99kev** [comment]
Thank you for the reply!

I will see if I can incorporate their respective controllers in the meantime 😄
