### ISSUE TITLE
create customized environment

### ISSUE THREAD

**Issue by SHITIANYU-hue** [ugr-sail/sinergym#341]
i was trying to create a customized building environment, i have added my file configuration but it still says cannot find the environment

![image](https://github.com/ugr-sail/sinergym/assets/38762389/22bd1906-9e62-4dad-b29f-56819e026437)

![image](https://github.com/ugr-sail/sinergym/assets/38762389/9bd901b7-375e-4488-85d5-58c4ae3bb498)

**Comment by AlejandroCN7** [comment]
Hi @SHITIANYU-hue,
How did you install Sinergym? With `pip install sinergym`? With our container? We have created a bug template to be able to help users more efficiently. Please, **do not skip these templates** and use them for better communication. Please, fill the next information:

### System Info

Describe the characteristic of your environment:
 * Describe how Sinergym was installed: (pip, docker, source, ...)
 * Sinergym Version: e.g. 2.3.0
 * OS: e.g. Ubuntu 22.04 LTS or Dockerfile
 * Python version: e.g. 3.10 or Dockerfile
 * Gymnasium version:

I suspect the problem is that you installed Sinergym using the PyPi repo. Therefore, your local changes do not affect your Sinergym package. And you should use `pip install -e .[extras]` in the root path of your cloned repository (if you are using our container, you shouldn't have this problem).

**Comment by SHITIANYU-hue** [comment]
I used the docker's default installation, i used my vs code connects to the docker image( https://code.visualstudio.com/docs/devcontainers/containers). Also, I tried to reinstall Sinergym again in my docker, thanks for your reply, I will try to see if there is any step that I missed.

**Comment by AlejandroCN7** [comment]
@SHITIANYU-hue see [this](https://github.com/ugr-sail/sinergym/issues/288#issuecomment-1434468386).

**Comment by SHITIANYU-hue** [comment]
Hello, thanks!

I tried to run it in my docker container and it works. However, when i import my environment, i.e., env=gym.make('Eplus-taicang'), it has this error, may i know if there is anything wrong with my taicang.idf file? 

<img width="1059" alt="image" src="https://github.com/ugr-sail/sinergym/assets/38762389/25c634d0-0587-41ba-bcc5-52569c568612">
