### ISSUE TITLE
[Question][Help] Need help with installation

### ISSUE THREAD

**Issue by Hnecent** [ugr-sail/sinergym#399]
Dear sinergym,

I followed the installation steps and downloaded the docker container. I cloned the repository and work in Pycharm now on a windows. I am getting the following error when trying the examples that were given:

![image](https://github.com/ugr-sail/sinergym/assets/73325257/7d0b128e-4bfb-4eee-be78-f8252eca08a4)

I hope you can help me with this problem!

Best,
Xiao

**Comment by AlejandroCN7** [comment]
Hello @Hnecent,

I'm sorry to hear about the issue you're experiencing.

While I'm not exactly sure what the problem might be without more information, here are a few suggestions:

1. Ensure that you are within the Docker container.
2. Please refer to this issue, specifically [this response](https://github.com/ugr-sail/sinergym/issues/288#issuecomment-1434468386), to make sure you're not encountering the same problem.
3. You also need to ensure that your workspace has the environment variable PYTHONPATH set, and that it includes the path `/usr/local/EnergyPlus-${ENERGYPLUS_INSTALL_VERSION}`. If for some reason your EnergyPlus installation is located elsewhere, please specify that, as otherwise the interpreter won't recognize the pyenergyplus library.
4. Make sure you're working with the latest version of Sinergym to avoid any bugs that have already been fixed.

I hope this helps! Please let me know if you have any other questions.

Best regards!

**Comment by Hnecent** [comment]
Thank you for your reply, I think I found the problem, it is because I use this image in pycharm and pycharm will recreate the helper container to run the image, but then the environment variables will be lost. The container I created directly using this image does not have this problem. Thanks again for your help!
